#!/bin/bash
set -euo pipefail

APP_NAME="PhotoSnail"
EXECUTABLE="photo-snail-gui"
BUILD_DIR=".build/release"
APP_DIR="${BUILD_DIR}/${APP_NAME}.app"

echo "Building ${EXECUTABLE}..."
swift build -c release --product "${EXECUTABLE}"

echo "Packaging ${APP_DIR}..."
rm -rf "${APP_DIR}"
mkdir -p "${APP_DIR}/Contents/MacOS"
mkdir -p "${APP_DIR}/Contents/Resources"

cp "${BUILD_DIR}/${EXECUTABLE}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"

# App icon. Generated by `swift tools/make-icon.swift` + iconutil.
# Copying into Resources/ inside the bundle is what macOS expects; the
# CFBundleIconFile key below points to it (sans extension).
if [[ -f "Resources/AppIcon.icns" ]]; then
  cp "Resources/AppIcon.icns" "${APP_DIR}/Contents/Resources/AppIcon.icns"
else
  echo "warning: Resources/AppIcon.icns is missing — the app will launch with a generic icon."
  echo "         Regenerate with:  swift tools/make-icon.swift && iconutil -c icns Resources/AppIcon.iconset -o Resources/AppIcon.icns"
fi

# Sidebar wordmark. Also produced by tools/make-icon.swift, displayed at
# the top of the app's sidebar via Bundle.main.url(forResource:…).
if [[ -f "Resources/LogoWordmark.png" ]]; then
  cp "Resources/LogoWordmark.png" "${APP_DIR}/Contents/Resources/LogoWordmark.png"
else
  echo "warning: Resources/LogoWordmark.png is missing — sidebar header will fall back to text."
fi

# Light-mode variant of the sidebar wordmark (dark text for light backgrounds).
if [[ -f "Resources/LogoWordmarkLight.png" ]]; then
  cp "Resources/LogoWordmarkLight.png" "${APP_DIR}/Contents/Resources/LogoWordmarkLight.png"
fi

# Build stamp: human-readable date and monotonic build number.
# BUILD_DATE is displayed in the About box; CFBundleVersion takes a compact
# numeric form so macOS's version-comparison logic still sees builds as
# monotonically increasing.
BUILD_DATE="$(date '+%Y-%m-%d %H:%M:%S')"
BUILD_NUMBER="$(date '+%Y%m%d%H%M')"

# Git-derived version. `git describe --tags --always --dirty`:
#   - With a tag at HEAD         → "v1.0.0"
#   - N commits past a tag       → "v1.0.0-3-gabc1234"
#   - With uncommitted changes   → "...-dirty"
#   - No tags yet                → the abbreviated commit hash
# Falls back to "unknown" if git isn't available or this isn't a repo.
GIT_VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo unknown)"

cat > "${APP_DIR}/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>PhotoSnail</string>
    <key>CFBundleIdentifier</key>
    <string>com.laurentchouinard.photo-snail-gui</string>
    <key>CFBundleName</key>
    <string>PhotoSnail</string>
    <key>CFBundleVersion</key>
    <string>${BUILD_NUMBER}</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>PhotoSnailBuildDate</key>
    <string>${BUILD_DATE}</string>
    <key>PhotoSnailGitVersion</key>
    <string>${GIT_VERSION}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>PhotoSnail reads your Photos library to generate descriptions and tags for each photo using a local AI model.</string>
    <key>NSPhotoLibraryAddUsageDescription</key>
    <string>PhotoSnail writes AI-generated descriptions and tags back to your Photos library metadata.</string>
    <key>NSAppleEventsUsageDescription</key>
    <string>PhotoSnail drives Photos.app via AppleScript to write descriptions that sync via iCloud.</string>
    <key>NSHumanReadableCopyright</key>
    <string>MIT License</string>
</dict>
</plist>
PLIST

echo -n "APPL????" > "${APP_DIR}/Contents/PkgInfo"

echo ""
echo "Done: ${APP_DIR}"
echo "  open '${APP_DIR}'"
echo "  cp -R '${APP_DIR}' /Applications/   # to install"
